version: "3.9"

services:
  testapp:
    container_name: app
    build:
      context: .
    networks:
      default:
        aliases:
          - testapp
      infrastructure_lab:
        aliases:
          - testapp
    entrypoint: /main
    expose:
      - 8080
      - 8443
    ports:
      - "8080:8080"
      - "8443:8443"

networks:
  default: {}
  infrastructure_lab:
    external: true