global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    static_configs:
      - targets: ['app:8080']
  # - job_name: app
  #   scheme: https
  #   tls_config:
  #     insecure_skip_verify: true
  #   static_configs:
  #     - targets: ['app:8443']