{
 "title": "Sample App",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "environ", "label": "environ", "query": { "query": "label_values(environ)" } },
   { "name": "hostname", "label": "hostname", "query": { "query": "label_values(hostname)" } },
   { "name": "appname", "label": "appname", "query": { "query": "label_values(appName)" } }
  ]
 },
 "panels": [
  {
   "title": "Increase In Requests [By Path]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(sample_app_requests_total{environ=\"$environ\",appName=\"$appname\",hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Increase In Errors [By Path]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "increase(sample_app_response_errors{environ=\"$environ\",appName=\"$appname\",hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{path}} [{{errorType}}]"
    }
   ]
  },
  {
   "title": "Avg Response Time(ms) [By Path]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (path) (sample_app_response_time{environ=\"$environ\",appName=\"$appname\",hostname=~\"$hostname\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Response Rate [By Path]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path, errorType) (sample_app_response_errors{environ=\"$environ\",appName=\"$appname\",hostname=~\"$hostname\"})",
     "legendFormat": "{{errorType}} [/{{path}}]"
    }
   ]
  },
  {
   "title": "Response Status [By Path]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sample_app_response_status{environ=\"$environ\",appName=\"$appname\",hostname=~\"$hostname\"}[$__rate_interval]), 1)",
     "legendFormat": "{{path}} [{{statusCode}}]"
    }
   ]
  },
  {
   "title": "Error Response Rate [By Path]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sample_app_response_errors{environ=\"$environ\",appName=\"$appname\",hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{errorType}} [/{{path}}]"
    }
   ]
  }
 ]
}