version: "3.9"

services:
  crdb:
    container_name: node_1
    build:
      context: .
    volumes:
      - ./_crdb/node_1/data:/cockroach/cockroach-data
      - ./_crdb/node_1/certs:/cockroach/certs
    networks:
      default:
        aliases:
          - crdb
      lab:
        aliases:
          - crdb
    entrypoint: /cockroach/init_crdb.sh
    expose:
      - 8080
      - 26257
    ports:
      - "8888:8080"
      - "26257:26257"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.44.0
    volumes:
      - ./_prometheus:/etc/prometheus
    networks:
      default:
        aliases:
          - prometheus
      lab:
        aliases:
          - prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.3
    user: "0"
    volumes:
      - ./_grafana:/var/lib/grafana
    networks:
      default:
        aliases:
          - grafana
      lab:
        aliases:
          - grafana
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    # volumes:
    #   - ./_grafana:/var/lib/grafana
    networks:
      default:
        aliases:
          - jaeger
      lab:
        aliases:
          - jaeger
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"



networks:
  default: {}
  lab:
    driver: bridge